project_id = "syqawvakxxfaohcgrenn"

[functions.send-campaign-emails]
verify_jwt = true

[functions.track-email]
verify_jwt = false

[functions.process-scheduled-campaigns]
verify_jwt = false

[functions.process-follow-ups]
verify_jwt = false

[functions.match-email-replies]
verify_jwt = false
